eureka:
  client:
      registerWithEureka: true
      fetchRegistry: true
      service-url:
          defaultZone: http://estock-eureka-elb-968939317.ap-south-1.elb.amazonaws.com/eureka/
  instance:
      hostname: localhost
    
